<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_OK_fal fa-folder</name>
   <tag></tag>
   <elementGuidId>7a6de8ac-70b9-4e2c-aba3-0fcfb8a09f24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header-projectfolder']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fal.fa-folder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c5b43e78-8e8f-46f2-8b5e-e1bd151661f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fal fa-folder</value>
      <webElementGuid>d2892bf2-dc1e-467c-a648-4d0fd3a0eb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-projectfolder&quot;)/i[@class=&quot;fal fa-folder&quot;]</value>
      <webElementGuid>f673c3c1-8cb3-4073-b945-9ce73bec460c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='header-projectfolder']/i</value>
      <webElementGuid>4179cf38-4bb9-4ee2-8b0b-3f49ca3073cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/i</value>
      <webElementGuid>507fdc56-367b-4d32-a58b-317399e86cc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
