<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Africa</name>
   <tag></tag>
   <elementGuidId>83169c24-bc30-4c96-b27b-43e576d81d98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='v-pills-home-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#v-pills-home-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26d4befc-3e7e-4559-a3bd-dd6a14a93864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>d6b7ef9f-3592-43f1-8af9-de4c1b2554d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>v-pills-home-tab</value>
      <webElementGuid>2024ea8e-d0f4-48ea-ac90-8af540d1ef64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>f014dcc7-ca7c-45bf-8b02-100b54dc4ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location1</value>
      <webElementGuid>05b5dcf4-93ec-4c84-a443-2c06aacbe821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>bfa55415-c7ce-4643-a121-016da2b43c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location1</value>
      <webElementGuid>31bb0355-fb2a-4715-8bd9-18bd98201cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e136336-95fe-404b-aa35-a098403da513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Africa</value>
      <webElementGuid>3f43511b-5c03-4066-8fb7-82d85e0c88a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@id=&quot;v-pills-home-tab&quot;]</value>
      <webElementGuid>1e60236e-aa3d-46b9-9627-1e35303ee179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b723e118-6233-4ea3-95ee-bb66569a031b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>a3a5639c-8623-4e66-9b9d-442adf8570fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>v-pills-home-tab</value>
      <webElementGuid>dffeefc5-9c4b-447e-b9c8-50836bcfee4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>4fca5516-e150-4674-b36e-9f0453e3f316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location1</value>
      <webElementGuid>a0ede97e-1705-4bf3-8f8b-f6691dbb1ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c3530555-acff-41ae-93c1-b530e98ad95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location1</value>
      <webElementGuid>40111eea-24d6-4f38-b4b3-5cc8bf4a9895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4764c866-6427-4158-b123-be889f8245c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Africa</value>
      <webElementGuid>3af0a122-d83d-438b-9814-71c11df9e565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@id=&quot;v-pills-home-tab&quot;]</value>
      <webElementGuid>6b150383-9dca-48fa-9210-80d9b8be0353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='v-pills-home-tab']</value>
      <webElementGuid>d1bc0889-0b1a-4dcb-af2d-f09efeb77d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-location']/div/div/div[2]/div/div/a</value>
      <webElementGuid>07d88ba8-ab1c-4ef4-bcc0-fe885e55e605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Africa')]</value>
      <webElementGuid>8b5f3121-a0cd-441b-93a9-2a28c17870ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Project Location'])[1]/following::a[1]</value>
      <webElementGuid>daeabdbf-5de5-4ae8-b492-afc9a7f297ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::a[4]</value>
      <webElementGuid>9dbefce7-3c99-49af-a542-a08eb7958520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Americas'])[1]/preceding::a[1]</value>
      <webElementGuid>ce520ed9-b796-48d5-b89e-cd7010d7ede5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia'])[1]/preceding::a[2]</value>
      <webElementGuid>84962bcb-481d-4570-8a4e-ab3500325dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Africa']/parent::*</value>
      <webElementGuid>ceb1f30d-6249-4e44-9e5e-3036e0a0d437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#location1')]</value>
      <webElementGuid>0e68d773-2aa1-4585-83f4-53af4d60d6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>150bb41a-cdc3-49ed-8f55-5c991b1d7f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'v-pills-home-tab' and @href = '#location1' and (text() = 'Africa' or . = 'Africa')]</value>
      <webElementGuid>1815bac7-c5a8-4644-b297-44442774558a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
