<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Americas</name>
   <tag></tag>
   <elementGuidId>fce104fc-ed90-42ef-867a-bece08df2823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-location']/div/div/div[2]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>affe7bc5-3188-4cfd-88eb-684e33a0252f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>01d3e67d-02ea-499e-b73c-1f79156c55a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>464d1b47-741a-4fe4-9f37-4ed649f6495c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location2</value>
      <webElementGuid>af5bdca3-bc6d-41b1-a41e-22ce2f3646b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6ddf96ca-56b3-4c7c-8b63-9e5d3792f22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location2</value>
      <webElementGuid>98a6d9fc-4b55-45f3-9899-52359e652b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>264d7ada-6c86-41a3-8a8f-5a4ca3458662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Americas</value>
      <webElementGuid>2009af7c-f9b0-486b-ba29-5f8075fd10ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase&quot;]</value>
      <webElementGuid>c8715ede-2ac6-4db9-a4b9-fbffe064a46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85c68be2-efdf-4262-9c43-5f8ca8e00358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>b6152313-5662-4a68-a939-272469a6183e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>14637e9a-e201-4796-b433-fc713f4b59d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location2</value>
      <webElementGuid>440635dd-9fe0-407c-b478-cfa696678d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5aeaa2b8-1289-4455-af0e-744bbd0b30cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location2</value>
      <webElementGuid>709028dd-7fc8-4401-a466-3b193bf52cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc0b6a91-c895-463e-a139-e4e6df772cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Americas</value>
      <webElementGuid>35808b9f-23c1-4a63-b8eb-74a0244464b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase&quot;]</value>
      <webElementGuid>f083a21c-f794-4f60-8c09-26051a81c9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69f8ada0-cb2e-4a59-a83f-4ecf4f225594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>6c7846c7-e63f-481c-9748-3bb523e27799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>a913a53d-3397-4f15-a793-25e243e8684e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location2</value>
      <webElementGuid>39c037c4-7be1-4935-9f31-92d3df0d866c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>37a6a098-a119-498b-826a-4c359f96451e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location2</value>
      <webElementGuid>1e6429e0-cae5-4a6c-967a-928fb03fe76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7464b722-87c1-477b-9042-1cf6a3f32292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Americas</value>
      <webElementGuid>da73c5ce-dba8-4329-b6fb-988c00900ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase&quot;]</value>
      <webElementGuid>6f2087df-25fd-42ee-a0b2-f6a71183af65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>293b0943-e8e3-4425-95ed-0fb00b69d184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>20a932c6-6df7-41df-84bb-e72a25e83fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>4e590ef6-9684-486f-827f-70ba3dd528c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location2</value>
      <webElementGuid>bf827ac3-47d5-49f3-8a5e-ad665966cae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>acf183a1-8d0a-4a65-b73f-548c9a74f0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location2</value>
      <webElementGuid>bef2a790-b742-4532-b5b5-2b646b3002bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a54719e-ad67-4a49-be55-12208c5a2865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Americas</value>
      <webElementGuid>a20c07ac-34db-463c-b1b9-2a5b5a2dd886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase&quot;]</value>
      <webElementGuid>2ed98a0d-d0e4-4d13-a964-c883e6767503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-location']/div/div/div[2]/div/div/a[2]</value>
      <webElementGuid>1b61f7c0-d250-45fe-84d1-24e3b341a96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Americas')]</value>
      <webElementGuid>26505342-272b-4193-9fef-89cf5250bc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Africa'])[1]/following::a[1]</value>
      <webElementGuid>2293ecb1-44f5-46d4-9b08-0e1635893497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Project Location'])[1]/following::a[2]</value>
      <webElementGuid>fad16781-1009-4f80-817b-65eae722b463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia'])[1]/preceding::a[1]</value>
      <webElementGuid>18ba140e-1c6e-41ea-bf10-69a98dea687b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australasia'])[1]/preceding::a[2]</value>
      <webElementGuid>3152ac41-8ba8-498e-9462-6a3bf1a6396e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Americas']/parent::*</value>
      <webElementGuid>129e209c-b61f-4792-8964-9f4ce438da83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#location2')]</value>
      <webElementGuid>0a8d8033-e57c-4408-ad85-b076305a362f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a[2]</value>
      <webElementGuid>4c1f6aae-4133-4282-81ad-122a0d1088ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#location2' and (text() = 'Americas' or . = 'Americas')]</value>
      <webElementGuid>d0983301-6383-4da9-862b-6c5a58cda773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
