<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Asia</name>
   <tag></tag>
   <elementGuidId>a578ae43-fcb7-4866-a431-edd2d10e5d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-location']/div/div/div[2]/div/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f328937-98af-476c-989b-9a6f07461046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>f8a48680-ebfb-456f-8bf2-f50fece2b98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>91a42892-1236-4b24-85f8-2b18fd825a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location3</value>
      <webElementGuid>601dad4a-257e-4416-aa1a-2791d728d5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>51d4681c-445a-4139-bf3a-d6108f49ce19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location3</value>
      <webElementGuid>3a340d5a-2082-4eea-8219-dc54fe07e94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>acb8e2c9-4c76-4c74-afc4-560ec0e4720d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asia</value>
      <webElementGuid>eeb89605-b625-4e5e-804e-fa8b6518f457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase&quot;]</value>
      <webElementGuid>ffe66242-3ef9-4cc8-a206-7f455b4d4e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08104222-2a56-4871-b078-20e9e2f842eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase active</value>
      <webElementGuid>8ddc5019-a1f8-40bd-b9b4-d75fbecb65fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>351b263f-b6f3-4d9c-9bd4-1d0389f1f271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location3</value>
      <webElementGuid>f72a83e1-25f6-464d-b4f5-2521f8ca51a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>23d1417f-b80a-455b-94b8-404951deadbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location3</value>
      <webElementGuid>23c6b9a7-08de-4e9a-881f-3d68e31b5306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e7213f9f-24db-4c40-b053-ecdb5811b0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asia</value>
      <webElementGuid>cf8641e9-b964-41ce-a239-ca48c2d0143f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase active&quot;]</value>
      <webElementGuid>88ecfa24-6943-4090-8c1e-071b76edf99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-location']/div/div/div[2]/div/div/a[3]</value>
      <webElementGuid>4ea8934a-4ab1-4c1f-9f93-a0b1bfb4a745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Asia')]</value>
      <webElementGuid>3d7d7a8b-384c-4d8d-90a1-24bc1f975b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Americas'])[1]/following::a[1]</value>
      <webElementGuid>52e35382-b2f7-4cae-9bc6-6b7dfeacb59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Africa'])[1]/following::a[2]</value>
      <webElementGuid>52621113-11ae-47e4-a048-b0cc4b105f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australasia'])[1]/preceding::a[1]</value>
      <webElementGuid>947abf8e-d19b-4e8d-82f8-516c8e6a8df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe'])[1]/preceding::a[2]</value>
      <webElementGuid>8d8ee261-bb8b-4079-a57c-0cc65455f894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Asia']/parent::*</value>
      <webElementGuid>267a9cc5-13e7-43f7-9f87-30dd7371a264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#location3')]</value>
      <webElementGuid>05fe0f09-7bcc-4e25-804d-51016300ea1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a[3]</value>
      <webElementGuid>c3617f35-1c03-4ee2-8532-5765df2d2b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#location3' and (text() = 'Asia' or . = 'Asia')]</value>
      <webElementGuid>04d48728-6003-4d44-aded-660bbde680a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
