<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bangladesh</name>
   <tag></tag>
   <elementGuidId>14331b8c-8b06-491b-8fec-060aa6283704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Bangladesh']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Bangladesh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>764d5614-3d66-4020-b493-1bd8a808ac81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>fc0873e0-a2fe-4f6b-a6b3-82076b94a341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0</value>
      <webElementGuid>be051bbd-2b67-4232-b86e-6e035e8a823f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-countrycode</name>
      <type>Main</type>
      <value>BD</value>
      <webElementGuid>d87a235b-2c22-4b8c-979e-bfb79ad0587b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-value</name>
      <type>Main</type>
      <value>Bangladesh</value>
      <webElementGuid>9881ad79-0560-4f0c-98f2-3a32dabf3cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Bangladesh</value>
      <webElementGuid>1440c2d1-7d6f-4efa-9cba-04b24fbe5a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bangladesh</value>
      <webElementGuid>438ed9a9-6b11-4ccd-a67f-0d04eef686c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location3&quot;)/ul[@class=&quot;tab-pane-location float-left d-flex flex-wrap flex-column list-unstyled L2navigation2&quot;]/li[@class=&quot;region&quot;]/a[@id=&quot;Bangladesh&quot;]</value>
      <webElementGuid>fee7e0ce-d336-4c71-8d02-aca4c3980d3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Bangladesh']</value>
      <webElementGuid>6e3b113b-fe20-489d-9cdf-e63de8dc6799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location3']/ul/li/a</value>
      <webElementGuid>b94e66e7-8cc0-49bc-9870-a0a8f53475e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bangladesh')]</value>
      <webElementGuid>dccc1dcc-ed0f-4f47-9fce-83b52d0f714b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle East'])[1]/following::a[59]</value>
      <webElementGuid>20cfec74-8311-46b9-9c5d-f12a38552d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe'])[1]/following::a[60]</value>
      <webElementGuid>c88f666a-6531-4f0b-9300-63022d8d77f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/preceding::a[40]</value>
      <webElementGuid>edfedec9-31c4-4be8-b480-36226184f5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::a[47]</value>
      <webElementGuid>5cedc6e5-88a9-4d08-94aa-51067054c53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bangladesh']/parent::*</value>
      <webElementGuid>3c18685e-9d20-42cb-8144-750b84da30e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[67]</value>
      <webElementGuid>1dd9e1e9-77a8-45cf-a47d-0fed0f319099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/a</value>
      <webElementGuid>d8465eeb-a3b4-468a-a7a2-76cf1dc65eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'Bangladesh' and (text() = 'Bangladesh' or . = 'Bangladesh')]</value>
      <webElementGuid>81955b9d-efa6-4a08-8df4-3e937c579c86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
