<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Botswana</name>
   <tag></tag>
   <elementGuidId>e6a2d9b4-2458-445d-b55f-490cc72f787f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Botswana']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Botswana</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7249b745-6be5-4839-9cd4-5f581bf582db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a3817f6a-030e-42bb-b833-580cc7be229f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0</value>
      <webElementGuid>208007f4-e40d-4d40-9cce-1033050f5fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-countrycode</name>
      <type>Main</type>
      <value>BW</value>
      <webElementGuid>bef369d2-3f60-4fda-9754-fa39df220e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-value</name>
      <type>Main</type>
      <value>Botswana</value>
      <webElementGuid>03712dc0-902c-4a98-a7c4-0de6007f8b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Botswana</value>
      <webElementGuid>19cbcc6c-6705-41e3-8be0-39dc3124a613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Botswana</value>
      <webElementGuid>9c1f8861-2eca-4b8f-a113-bce1bf71b634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location1&quot;)/ul[@class=&quot;tab-pane-location float-left d-flex flex-wrap flex-column list-unstyled L2navigation0&quot;]/li[@class=&quot;region&quot;]/a[@id=&quot;Botswana&quot;]</value>
      <webElementGuid>e9160cc5-5643-4bb5-9309-d742581f6978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Botswana']</value>
      <webElementGuid>d2dfe96d-be9a-4a98-a83a-372ef27ab487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location1']/ul/li[2]/a</value>
      <webElementGuid>e456e536-8b50-4df7-b36a-3e0187ce581c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Botswana')]</value>
      <webElementGuid>1430ccda-1860-488d-9b1e-dbcd94ba910b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle East'])[1]/following::a[2]</value>
      <webElementGuid>ca7df189-c279-4f0b-894e-b73e1b4a8a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe'])[1]/following::a[3]</value>
      <webElementGuid>f69acfd3-4890-4a5d-8bca-d366db352c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/preceding::a[97]</value>
      <webElementGuid>a91e21ec-601d-47dc-9e82-8e0c375744e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::a[104]</value>
      <webElementGuid>c1e2fecc-12a3-468c-a3c4-ac442a2bf21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Botswana']/parent::*</value>
      <webElementGuid>57c2ddc0-8ac0-4d81-930f-c6f28571f96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>357580cc-76fc-4bbf-9ac0-94d9b042a3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>1e1612ac-e57e-4dcc-a3a8-704ab98def7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'Botswana' and (text() = 'Botswana' or . = 'Botswana')]</value>
      <webElementGuid>d4b257fb-f7a1-4519-ac90-cb0e192575ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
