<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact Us</name>
   <tag></tag>
   <elementGuidId>6f720bba-a9c5-4866-b2b2-d27486d2bafb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#redirectContactUsCTA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='redirectContactUsCTA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>587c8afa-fdec-431a-8d47-cd69a03a688d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caption-typ</value>
      <webElementGuid>281baa06-e79d-4dcb-bb28-680d2957c7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-us/contact-us</value>
      <webElementGuid>c2668661-c8af-40cb-a1fd-ec5fe0771ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redirectContactUsCTA</value>
      <webElementGuid>125a82f2-8fdb-4c01-bd80-d90cf568b396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Us</value>
      <webElementGuid>3fe5103b-0654-433d-ae24-1134cd7e88e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redirectContactUsCTA&quot;)</value>
      <webElementGuid>6702e2a2-b9af-40b8-b633-b68512d974b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='redirectContactUsCTA']</value>
      <webElementGuid>38d19afa-5c30-44fd-9da2-522247e258e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Contact Us')])[9]</value>
      <webElementGuid>1bc97b80-eaac-4b04-838b-47215453dc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQs'])[1]/following::a[1]</value>
      <webElementGuid>01fb8b27-1392-4290-a5dd-600862bfdb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::a[2]</value>
      <webElementGuid>0993c3bf-c628-4a10-872c-7a5b2dbc6aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sitemap'])[1]/preceding::a[1]</value>
      <webElementGuid>2aaeed79-097c-43a9-9d7b-c1194170657e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Us'])[1]/preceding::a[2]</value>
      <webElementGuid>bb66cb3a-3a20-402e-b4b2-4eac3d554cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en-us/contact-us')])[20]</value>
      <webElementGuid>bdc6b6d5-b1ac-4eb2-8bd0-89bd8d809dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div[2]/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>dd83b774-2fff-4831-8f47-ed342c3b8e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-us/contact-us' and @id = 'redirectContactUsCTA' and (text() = 'Contact Us' or . = 'Contact Us')]</value>
      <webElementGuid>8d9bb33c-3125-4f5b-9e4c-67191d12a86b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
