<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Europe</name>
   <tag></tag>
   <elementGuidId>f8275634-41f6-4c40-8789-4b65d937e739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-location']/div/div/div[2]/div/div/a[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71c3ede8-1dd8-492a-bc99-fd0e0823850f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>c4e19240-5158-4734-a461-aec22abeb6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>26a1737c-5148-4719-bb28-8645d5bd0549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location4</value>
      <webElementGuid>f962f297-9671-4c11-87d1-66df41f4556e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>11df2db3-d265-418b-ad0f-2e681e43601d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location4</value>
      <webElementGuid>25b56886-04b8-4986-b4b8-99a66ce3b704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec507130-fbf5-4967-9d85-34a6b5674c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Europe</value>
      <webElementGuid>ba93642f-5d9b-483e-9656-8ec14cc68ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase&quot;]</value>
      <webElementGuid>8593cc09-d7bd-40b8-9324-141a0c5a3140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85255143-7923-4d31-ad9d-0f4974075516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>baebc076-c0d8-45c4-9666-9e7cb9e4741c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>eae6e0f2-591b-48ea-bb31-554b1efaae5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location4</value>
      <webElementGuid>d6ee3485-bfa1-4c77-8387-6e157ca7b276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b95af1c3-2dc1-4f27-ada7-11cc0a7d5e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location4</value>
      <webElementGuid>82e4d10c-a460-4cf4-b355-da5296661da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>94c78835-df11-4ff2-819a-01be8d36ebe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Europe</value>
      <webElementGuid>ab4f4753-33e3-4ac1-883c-8e4aa0a61fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase&quot;]</value>
      <webElementGuid>91ecdcea-09f5-42f4-83be-a86a39cb2de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-location']/div/div/div[2]/div/div/a[5]</value>
      <webElementGuid>f3d20297-28a7-4025-85d7-9dca9d413a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Europe')]</value>
      <webElementGuid>e23fecb2-3850-44e0-bab8-3737654da8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australasia'])[1]/following::a[1]</value>
      <webElementGuid>46b7be11-42eb-400d-831b-d1389da88325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia'])[1]/following::a[2]</value>
      <webElementGuid>e98f3f4f-fee0-4e23-9e3c-b0ed88b461fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle East'])[1]/preceding::a[1]</value>
      <webElementGuid>d7ceb04f-d9b2-4784-980c-de7a04bdbbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/preceding::a[100]</value>
      <webElementGuid>381d013c-80f7-48e0-9ee4-c7e2cc3e7ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Europe']/parent::*</value>
      <webElementGuid>aa0b9b5b-03f6-49d2-bdb6-534d68dad152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#location4')]</value>
      <webElementGuid>0b91a499-bcde-4ffa-8a22-46236147048d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>1ec5a0f8-4e3e-45e9-ba1c-213bae9b5f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#location4' and (text() = 'Europe' or . = 'Europe')]</value>
      <webElementGuid>46d80a50-d59d-4977-b324-2248cbb317d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
