<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Events</name>
   <tag></tag>
   <elementGuidId>06a28ef4-b407-4e39-99e3-ba1f54081461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-d-tab5']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.body2-typ.main-nav.nav-link.animated-header.text-uppercase.px-0.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76042f8d-b479-43d0-bf40-75da1c854f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>body2-typ main-nav nav-link animated-header text-uppercase px-0 active</value>
      <webElementGuid>5a20a02f-c566-4fe8-9338-9544b0e67f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-us/featured-events/design-events</value>
      <webElementGuid>0ce647a1-d880-4ead-9ae3-a515e275c02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Events</value>
      <webElementGuid>3b0eb470-f930-4c48-b85b-adacfb5c9a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-d-tab5&quot;)/a[@class=&quot;body2-typ main-nav nav-link animated-header text-uppercase px-0 active&quot;]</value>
      <webElementGuid>b0f7e47e-7187-4181-8702-59154179bdf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-d-tab5']/a</value>
      <webElementGuid>7434db28-9311-407f-86ce-920843deb5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Events')]</value>
      <webElementGuid>38c3bdb6-0c81-4317-b60a-a91b928373bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kohler Podcasts'])[1]/following::a[4]</value>
      <webElementGuid>c3a60280-85fa-4451-9861-4638317a2608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artist Editions'])[1]/following::a[5]</value>
      <webElementGuid>c0c9c5eb-1256-4f0e-8efb-89d2ea1264d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our History'])[1]/preceding::a[2]</value>
      <webElementGuid>62c77f3e-a1c3-4cb7-ba95-37acfec3f5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kitchen &amp; Bath Brands'])[1]/preceding::a[3]</value>
      <webElementGuid>ab5d8aca-2d1e-4e0d-973c-b8cb29a8cecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Events']/parent::*</value>
      <webElementGuid>93a1faf5-2734-40cd-8ee4-d086dbc3e4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-us/featured-events/design-events')]</value>
      <webElementGuid>5a5d8fd8-e852-4bc2-9562-3f85ce0fd69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/ul/li[5]/a</value>
      <webElementGuid>e01bcf1e-e877-4ca7-9301-323a3a53936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-us/featured-events/design-events' and (text() = 'Events' or . = 'Events')]</value>
      <webElementGuid>ec33f08a-2416-4518-b162-7f8e921feca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
