<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FAQs</name>
   <tag></tag>
   <elementGuidId>c2ae8737-2f1b-4cfb-8707-24233c8ded56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.list-unstyled.footer-list.px-lg-0.subCategory2 > li.pt-3 > a.caption-typ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'FAQs')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ccbe4bb6-6a8c-49a1-9832-980ae46e0cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caption-typ</value>
      <webElementGuid>e69ff5e7-917a-44e6-893c-303fd915e04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-us/faqs</value>
      <webElementGuid>c0fa2869-940b-4b3a-b8bf-88f2b43a46bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FAQs</value>
      <webElementGuid>3dc04ebc-f67e-42c8-8a4f-fc6e6643983a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;articlepage page basicpage&quot;]/div[@class=&quot;root responsivegrid&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;experiencefragment aem-GridColumn aem-GridColumn--default--12&quot;]/div[@class=&quot;xf-content-height&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;footer aem-GridColumn aem-GridColumn--default--12&quot;]/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;footer-section pt-4  pt-lg-5  pb-0 pb-lg-3&quot;]/div[@class=&quot;row position-relative&quot;]/div[@class=&quot;col-lg-1 col-md-12 col-sm-12  help-text p-lg-0&quot;]/ul[@class=&quot;list-unstyled footer-list px-lg-0 subCategory2&quot;]/li[@class=&quot;pt-3&quot;]/a[@class=&quot;caption-typ&quot;]</value>
      <webElementGuid>42aba45d-8ef2-40f4-a9bc-81224f190787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FAQs')]</value>
      <webElementGuid>060f1bf2-6a06-4f13-9e4e-4d259a794ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::a[1]</value>
      <webElementGuid>d84dd3f2-d88d-48a1-a9af-64a84f12a804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Room'])[1]/following::a[2]</value>
      <webElementGuid>f6a6d5b8-1588-4d80-b70c-f54a5233d889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[10]/preceding::a[1]</value>
      <webElementGuid>62b11e58-13cd-4029-a767-c3fb1bed0f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sitemap'])[1]/preceding::a[2]</value>
      <webElementGuid>397263ee-793f-4289-acd2-ae9b1530020e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FAQs']/parent::*</value>
      <webElementGuid>5428ee66-2443-4817-beb1-aaf46da0988a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-us/faqs')]</value>
      <webElementGuid>ba2878b4-2852-4552-a33e-0ac33de26189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div[2]/div/div/div[2]/ul/li/a</value>
      <webElementGuid>5afd7fa0-984f-4a69-a2e7-a0434f3d61af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-us/faqs' and (text() = 'FAQs' or . = 'FAQs')]</value>
      <webElementGuid>c859189c-1792-4b79-b930-4ad50e6c968b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
