<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fiji</name>
   <tag></tag>
   <elementGuidId>c194512e-7015-44d1-9f94-c59f77e9080f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Fiji']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Fiji</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>702d637a-b2b5-415f-a4ec-f92f9e5dc76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8ced4418-90b7-459f-a840-f92ced4c19eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0</value>
      <webElementGuid>dff9814e-caa2-49e2-9560-b8cac1ed7d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-countrycode</name>
      <type>Main</type>
      <value>FJ</value>
      <webElementGuid>0100bc7f-51c6-4abd-9303-d1809216267c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-value</name>
      <type>Main</type>
      <value>Fiji</value>
      <webElementGuid>e854ba31-d7aa-4dec-9756-8bf055a26e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Fiji</value>
      <webElementGuid>22162f2e-810d-4d86-beb8-2f8e2ce0afc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fiji</value>
      <webElementGuid>160790ad-b4f0-4ced-b64e-0453bdc5e8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location6&quot;)/ul[@class=&quot;tab-pane-location float-left d-flex flex-wrap flex-column list-unstyled L2navigation3&quot;]/li[@class=&quot;region&quot;]/a[@id=&quot;Fiji&quot;]</value>
      <webElementGuid>22863f2d-456b-4b42-97a4-373ec73a95ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Fiji']</value>
      <webElementGuid>292e6712-7ff3-43c3-95cd-ec9081cb71d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location6']/ul/li[2]/a</value>
      <webElementGuid>a9c88e92-fc0a-4b01-90dd-ffb4ceb2169a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fiji')]</value>
      <webElementGuid>2d016122-eff5-48fa-9de3-8d6d94e6674c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle East'])[1]/following::a[84]</value>
      <webElementGuid>8140f058-3396-49a4-9070-b151761fb396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe'])[1]/following::a[85]</value>
      <webElementGuid>589337b8-61c6-4dd3-a7dc-a81c86e3e924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/preceding::a[15]</value>
      <webElementGuid>38387ede-31ef-450e-863e-4ba2fe642113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::a[22]</value>
      <webElementGuid>1e34a482-1cdd-4dc4-a757-b5f35b25daa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fiji']/parent::*</value>
      <webElementGuid>8afbc435-c261-4417-9daa-8f7f74aef210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[92]</value>
      <webElementGuid>ebcd36bc-d635-4d16-8cf0-e07fa4fa5b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]/a</value>
      <webElementGuid>e43661d3-2656-4a6d-bd92-ce8a46caa819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'Fiji' and (text() = 'Fiji' or . = 'Fiji')]</value>
      <webElementGuid>4044b3e1-335a-44f6-9cd0-ca6f2712c902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
