<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hong Kong, China</name>
   <tag></tag>
   <elementGuidId>1db876a2-3d3a-41f1-b2df-33d66d9385c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Hong-Kong']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Hong-Kong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0581f488-f261-48cb-ad1e-7ebd6616e145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c9a46206-729f-455c-8509-bb210349947f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0</value>
      <webElementGuid>83487ca2-0d44-49a1-ac4a-3f98d54e64d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-countrycode</name>
      <type>Main</type>
      <value>HK</value>
      <webElementGuid>8ae2819c-0807-498f-b67e-d5ac0d3c4e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-value</name>
      <type>Main</type>
      <value>Hong Kong</value>
      <webElementGuid>0f6c9500-46df-420c-b65f-7f6b6370ded0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Hong-Kong</value>
      <webElementGuid>a8691ec2-562d-4e57-b5d8-b51174765c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hong Kong, China</value>
      <webElementGuid>55d52153-3e90-4fb0-bb85-1f7dc4fae10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location3&quot;)/ul[@class=&quot;tab-pane-location float-left d-flex flex-wrap flex-column list-unstyled L2navigation2&quot;]/li[@class=&quot;region&quot;]/a[@id=&quot;Hong-Kong&quot;]</value>
      <webElementGuid>81d9b0b2-af44-4baa-a4c4-fcd9313d7017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Hong-Kong']</value>
      <webElementGuid>5c8ccf10-76ac-4afc-be48-c05a1186dc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location3']/ul/li[6]/a</value>
      <webElementGuid>136ccb74-06e7-4b3d-bbb0-0ab6b52cb3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hong Kong, China')]</value>
      <webElementGuid>927a9dda-2154-47bc-a524-b433bbe97e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle East'])[1]/following::a[64]</value>
      <webElementGuid>5a78ed48-8303-413a-ad74-54d9edff596c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe'])[1]/following::a[65]</value>
      <webElementGuid>6237c0d9-cb10-43cf-99a3-c45f46248294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/preceding::a[35]</value>
      <webElementGuid>a8320426-924b-493d-9b4a-089e3d839b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::a[42]</value>
      <webElementGuid>9eec42b8-a282-42fa-bc00-6f0a19544b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hong Kong, China']/parent::*</value>
      <webElementGuid>22be8ff4-3297-4ef9-becb-45562a7537b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[72]</value>
      <webElementGuid>5b9bea3e-b4c5-4745-8153-a610c00ce339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[6]/a</value>
      <webElementGuid>56be52da-4f2e-4adf-8c36-8539b1cca22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'Hong-Kong' and (text() = 'Hong Kong, China' or . = 'Hong Kong, China')]</value>
      <webElementGuid>d5cf5169-ffac-4b19-ae8b-fced188bbc78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
