<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Inspiration</name>
   <tag></tag>
   <elementGuidId>e71394e0-7669-4d26-8264-1e1b1d34d69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-d-perspectives']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-d-perspectives > a.body2-typ.main-nav.nav-link.dropdown-toggle.animated-header.text-uppercase.px-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3bc0dbf-49d6-4d9e-905a-e4472118489e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>body2-typ main-nav nav-link dropdown-toggle animated-header text-uppercase px-0</value>
      <webElementGuid>d29cc64c-576d-4a99-aaa7-1eef2d1cc2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8824e9ab-3e36-47cf-bcb9-62cdeaf109c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>7cdb6183-3a0c-4f5e-bff7-056fd0a52908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>ffb5dde2-19f6-4c3b-8626-53d8265468a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-delay</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>84022ade-392b-4fc2-aae4-97a605234060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inspiration</value>
      <webElementGuid>8a609194-9bbb-4a8f-a3ca-24240fbf8d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-d-perspectives&quot;)/a[@class=&quot;body2-typ main-nav nav-link dropdown-toggle animated-header text-uppercase px-0&quot;]</value>
      <webElementGuid>85c0399f-efd6-40f8-bfd5-08d2b981ff0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-d-perspectives']/a</value>
      <webElementGuid>bc0c0b7b-4065-4e30-a0c6-a10c24f73b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Inspiration')]</value>
      <webElementGuid>98d5f8bf-dbef-43ba-b191-9933add25d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT CUSTOMIZATION'])[1]/following::a[4]</value>
      <webElementGuid>ce5ea5df-71fe-4a3e-87d6-b51c23a69c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REQUEST PRODUCT SAMPLES'])[1]/following::a[5]</value>
      <webElementGuid>ed760c60-6dd8-42e2-ac4f-e2c0099d5216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project References'])[1]/preceding::a[1]</value>
      <webElementGuid>bb656b2d-3de3-48e8-97b5-ab892340a6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perspectives of the year'])[1]/preceding::a[2]</value>
      <webElementGuid>1bf99f28-ec91-4e71-8f04-6bd649414d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inspiration']/parent::*</value>
      <webElementGuid>7803ad30-edc2-4722-8b83-1863bb9741a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[120]</value>
      <webElementGuid>a7041cd1-b703-4874-9e7e-fc2fc8b051d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/ul/li[4]/a</value>
      <webElementGuid>db4b4e22-9628-4ddb-9760-ff099af69806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Inspiration' or . = 'Inspiration')]</value>
      <webElementGuid>6059db0e-5506-457c-82e0-8d2df34409ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
