<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Middle East</name>
   <tag></tag>
   <elementGuidId>67820ea2-8ff1-49eb-b649-b45cdb2ea6fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-location']/div/div/div[2]/div/div/a[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3ec86fa-13b6-4bb5-9298-458fa44a46e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>47282dcb-484a-4f3d-9dc5-aa7df6478817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>3d065a3a-4732-4cb6-9b83-bd1d2b247134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location5</value>
      <webElementGuid>09bbeaac-47ec-42ca-84d3-81787e3e7c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c4e087d7-ff04-48ac-a852-eab8a1a7d97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location4</value>
      <webElementGuid>9b93d744-ca3e-492d-bacd-3ca57ab3db4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b728fdf5-d552-4d86-9cf6-c2f0feb0bac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Middle East</value>
      <webElementGuid>43f1694a-9182-4404-bc6e-55cc297f1a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase&quot;]</value>
      <webElementGuid>501dd63d-d892-4bca-afed-e4207a7eae41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa3ec213-7a11-4b82-8b6f-c3524357f495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tab-link text-uppercase</value>
      <webElementGuid>7fd48740-2272-4634-81a2-6c3656e52a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>96693dbb-552b-4f74-868f-5fbb185499e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#location5</value>
      <webElementGuid>c10ec1cb-c13c-4870-8ded-074f1e37a436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>73641a54-794a-4cd6-becb-990e981b1994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>location4</value>
      <webElementGuid>93983bff-1adc-42c5-8655-d488131e4027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a67de857-2362-42b3-b07f-7c3f234c1144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Middle East</value>
      <webElementGuid>139b0f06-29ab-4fc4-9f9d-7e5020c525b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-location&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground p-0 mt-0 w-100 border-0 rounded-0 d-block show&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row region-selector-wrapper&quot;]/div[@class=&quot;col location-tab-heading-pane&quot;]/div[@class=&quot;nav&quot;]/a[@class=&quot;nav-link tab-link text-uppercase&quot;]</value>
      <webElementGuid>b72139b5-294b-4647-9b86-4f59cd105b61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-location']/div/div/div[2]/div/div/a[6]</value>
      <webElementGuid>4878de30-7208-47fb-bb55-9c2dd25faf5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Middle East')]</value>
      <webElementGuid>de565f28-d360-4feb-87f1-ca59ad6902d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe'])[1]/following::a[1]</value>
      <webElementGuid>959abf72-3869-4499-b9ed-ccbec5260ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australasia'])[1]/following::a[2]</value>
      <webElementGuid>8ec064cc-3d73-4b7d-81fb-55eea80411a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/preceding::a[99]</value>
      <webElementGuid>3811f2b6-e8fb-4f51-84e4-aad1b60d1a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::a[106]</value>
      <webElementGuid>223a6ae0-11d8-4a22-b631-abf162e5188a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Middle East']/parent::*</value>
      <webElementGuid>0ddfee05-1554-4ee4-b905-ad7bccfc0deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#location5')]</value>
      <webElementGuid>de581514-abc5-4c83-9a4e-3f55e5fd8aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>59055fc2-de90-44e5-8fad-aeed423a0348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#location5' and (text() = 'Middle East' or . = 'Middle East')]</value>
      <webElementGuid>49fe5ad9-bc3d-4512-a5df-41c690d3d65a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
