<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privacy</name>
   <tag></tag>
   <elementGuidId>f904ab83-f12a-4d6f-9fa0-bcfe0957e5f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Privacy')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2d7d100-4fda-4dec-af18-a5b789a1e5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-us/privacy-policy</value>
      <webElementGuid>af62d820-7598-4ce9-80eb-04d759d07318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy</value>
      <webElementGuid>319bf38b-57f1-49ff-a1ac-c13cd61bd559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;articlepage page basicpage&quot;]/div[@class=&quot;root responsivegrid&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;experiencefragment aem-GridColumn aem-GridColumn--default--12&quot;]/div[@class=&quot;xf-content-height&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;footer aem-GridColumn aem-GridColumn--default--12&quot;]/footer[1]/div[@class=&quot;footer-bot&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row px-0 copy-rights-text px-lg-0 px-md-0  py-3 py-lg-2&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 footer-policy px-lg-0&quot;]/label[@class=&quot;footer-typ pr-4 pr-lg-5 mb-0&quot;]/a[1]</value>
      <webElementGuid>0eccad83-448b-4983-b436-041ca97d0156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Privacy')]</value>
      <webElementGuid>cdf43fd7-c018-4d1a-b0e6-e494d48d68eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal'])[1]/following::a[1]</value>
      <webElementGuid>3622541a-c5ae-446d-a214-3d5e776e53ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CoBrowse code'])[1]/following::a[2]</value>
      <webElementGuid>ee7864e2-c439-4cd5-b3b9-204f9d6760d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject Access Request'])[1]/preceding::a[2]</value>
      <webElementGuid>13269db2-196a-44f9-b495-234f4b0e59b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© Kohler Co. All Rights Reserved'])[1]/preceding::a[3]</value>
      <webElementGuid>1fc1d2ad-ed61-4c12-97ba-b9e72d5413a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Privacy']/parent::*</value>
      <webElementGuid>01582ff6-3188-4451-ae69-56ae3ebcce96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en-us/privacy-policy')])[2]</value>
      <webElementGuid>b3e15ade-2b40-4434-8ae3-e09a6af39620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/a</value>
      <webElementGuid>614499b7-5168-4677-8690-afb687d4f41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-us/privacy-policy' and (text() = 'Privacy' or . = 'Privacy')]</value>
      <webElementGuid>0a2e75e6-1908-465c-b1df-b8198c44131d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
