<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Products</name>
   <tag></tag>
   <elementGuidId>1fd302f5-144e-4980-930d-283c1c47ca37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-d-product']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.body2-typ.main-nav.nav-link.dropdown-toggle.animated-header.text-uppercase.px-0.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1eeddda3-5f64-40e8-999e-6c5ecfa16baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>body2-typ main-nav nav-link dropdown-toggle animated-header text-uppercase px-0 active</value>
      <webElementGuid>e3696819-5466-4b56-9c25-0dadf3e47537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0e7376f3-edc9-4ea1-9811-a44ed70ee2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>a434d8e1-51bd-4d84-98dd-dfb280178c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>a4e6a748-44f4-46d6-a8fc-432ea6fc62d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-delay</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>d0c0758a-878b-4dc9-b35c-9ead894603c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>ed513ad4-38ca-44f8-a8df-f093b67c7644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-d-product&quot;)/a[@class=&quot;body2-typ main-nav nav-link dropdown-toggle animated-header text-uppercase px-0 active&quot;]</value>
      <webElementGuid>36772117-c2dd-4b8f-b3b9-3159bb09b836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-d-product']/a</value>
      <webElementGuid>4469678b-8039-49d8-b9b5-374be0bb9a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Products')]</value>
      <webElementGuid>4dd004b8-d8f4-4f08-a317-75fb450c6e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUGGESTED SEARCHES'])[1]/following::a[1]</value>
      <webElementGuid>9260f27e-88fb-4064-9421-f32c975dddc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bathroom'])[1]/preceding::a[57]</value>
      <webElementGuid>e8b1d697-b6ed-4584-a1d7-26250d27d310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toilets'])[1]/preceding::a[58]</value>
      <webElementGuid>6884778f-37e5-4f1c-ad5a-28385d4b351d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Products']/parent::*</value>
      <webElementGuid>c977f19c-ae4f-4456-967c-64b1f7291f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[114]</value>
      <webElementGuid>b987ab3c-1848-419f-8c95-536774f857e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/ul/li/a</value>
      <webElementGuid>01235b39-f6dd-4227-b37f-7eacdf8960ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Products' or . = 'Products')]</value>
      <webElementGuid>7e9bc06c-80b9-4023-810f-02fd95e2a4af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
