<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Toilets</name>
   <tag></tag>
   <elementGuidId>f01047b1-9ab4-4c5d-bf1c-f65ca123c6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-search']/div/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.s-result</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1761ed01-7832-48cf-b2e8-c8e332a9f0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-result</value>
      <webElementGuid>db9f1398-dcfe-4b17-97a4-31033c8fde3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toilets</value>
      <webElementGuid>db1de2b2-a214-4709-84f3-428bb6654afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search&quot;)/div[@class=&quot;dropdown-menu dropdowndarkbackground pt-0 mt-0 w-100 border-0 rounded-0 searchbar-desktop d-block show&quot;]/div[@class=&quot;container pt-5&quot;]/div[@class=&quot;col text-left flex-column search-result-header&quot;]/a[@class=&quot;s-result&quot;]</value>
      <webElementGuid>cc5110b6-0bd7-4e12-9aa1-3fb811b7112a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-search']/div/div/div[4]/a</value>
      <webElementGuid>c0622b6c-e421-447c-800b-7bd676a23de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUGGESTED SEARCHES'])[1]/following::a[1]</value>
      <webElementGuid>8d893d43-77ab-4188-b674-ca776f378f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='lets']/parent::*</value>
      <webElementGuid>83d01aa0-095c-404d-bc9e-ae84ff587f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>d4f0fad9-6f9c-4f4c-9133-05ffa08e0f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Toilets' or . = 'Toilets')]</value>
      <webElementGuid>5a91bfc3-61d0-4fe6-8132-39e00645c6fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
