<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_United Arab Emirates</name>
   <tag></tag>
   <elementGuidId>828df393-5b03-4427-add8-1fda40a51691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='United-Arab-Emirates']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#United-Arab-Emirates</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6dabefd6-77ed-466b-9759-bb5ed60397e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c06a97dd-5b12-453f-8f42-19da67aad94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0</value>
      <webElementGuid>0c819027-a620-4a17-bf2f-56103fbb20d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-countrycode</name>
      <type>Main</type>
      <value>AE</value>
      <webElementGuid>6fd1eb60-c96a-497e-8ce0-ebdc1a14dd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-value</name>
      <type>Main</type>
      <value>United Arab Emirates</value>
      <webElementGuid>30be1368-44e5-4ad3-b791-f8f62eefd541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>United-Arab-Emirates</value>
      <webElementGuid>8c0e22a6-5eb5-4046-9228-418e1e46d8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>United Arab Emirates</value>
      <webElementGuid>9a1fa9b0-2904-4378-a874-af33b9fba94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location5&quot;)/ul[@class=&quot;tab-pane-location float-left d-flex flex-wrap flex-column list-unstyled L2navigation5&quot;]/li[@class=&quot;region&quot;]/a[@id=&quot;United-Arab-Emirates&quot;]</value>
      <webElementGuid>d57c6ad8-27c7-4d58-915c-b80abaed3b81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='United-Arab-Emirates']</value>
      <webElementGuid>bc834d44-ff1b-4970-8111-d8990460822a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location5']/ul/li[11]/a</value>
      <webElementGuid>84fbab78-5474-4d31-a278-ef1027a225e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'United Arab Emirates')]</value>
      <webElementGuid>ad685cd1-fa83-4cfd-99ed-8a3837424dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle East'])[1]/following::a[98]</value>
      <webElementGuid>2c0dabf0-04ad-46cf-848a-de96d826a0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe'])[1]/following::a[99]</value>
      <webElementGuid>ee68a429-6fd3-46c3-80e0-b8ea42279389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/preceding::a[1]</value>
      <webElementGuid>6f5224d0-8ae4-4af1-8a3d-ec083e1a1460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::a[8]</value>
      <webElementGuid>7d6b73b8-22b6-42f5-af25-50189d732c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='United Arab Emirates']/parent::*</value>
      <webElementGuid>258f6229-df2b-4f8e-b149-fa6f7da019ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[106]</value>
      <webElementGuid>78eff6e6-3d7f-4d75-ae21-988617814b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li[11]/a</value>
      <webElementGuid>63f76ebd-c1c0-44e2-8fa1-ac1c5433d69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'United-Arab-Emirates' and (text() = 'United Arab Emirates' or . = 'United Arab Emirates')]</value>
      <webElementGuid>88ab416d-222a-487b-b5e1-02bb80051f7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
