<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_United Kingdom</name>
   <tag></tag>
   <elementGuidId>ad928279-80c2-4643-883c-7052a3e46607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='United-Kingdom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#United-Kingdom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0107b41-d6ca-4bca-9de3-ca909beb0be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4eea3675-bcd2-4e9c-82f3-814fa30622d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0</value>
      <webElementGuid>16e073d5-d47e-428f-8c1d-5e33762b278a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-countrycode</name>
      <type>Main</type>
      <value>GB</value>
      <webElementGuid>03ccc742-ef62-4d3d-a0e0-508df21e2a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-value</name>
      <type>Main</type>
      <value>United Kingdom</value>
      <webElementGuid>c58bd505-9f29-4082-b19b-679cf7ed5dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>United-Kingdom</value>
      <webElementGuid>1869fa7d-1c8d-4686-87a8-92f0a4632df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>United Kingdom</value>
      <webElementGuid>ea1c00f2-d4fd-44fc-b743-58a6d54ae0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location4&quot;)/ul[@class=&quot;tab-pane-location float-left d-flex flex-wrap flex-column list-unstyled L2navigation4&quot;]/li[@class=&quot;region&quot;]/a[@id=&quot;United-Kingdom&quot;]</value>
      <webElementGuid>ab5afc58-4c4f-4081-bbba-de067d5ccc66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='United-Kingdom']</value>
      <webElementGuid>1bc73789-34ef-4069-8707-9b50de53a752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location4']/ul/li/a</value>
      <webElementGuid>cdea8f7f-0d29-4d72-b5c7-19e9fe15de5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'United Kingdom')]</value>
      <webElementGuid>287d6977-251f-49cb-81d0-8d047aa4a664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle East'])[1]/following::a[87]</value>
      <webElementGuid>695004cd-cdf4-4f4a-9cda-9139e4e4faa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Europe'])[1]/following::a[88]</value>
      <webElementGuid>bdf26afd-4ca2-4157-9a2f-64ac616b9845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/preceding::a[12]</value>
      <webElementGuid>5d23a400-4397-4bf3-8a25-ce3f9deeafa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::a[19]</value>
      <webElementGuid>64d170e6-72bf-4956-b136-2eaf7055cd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='United Kingdom']/parent::*</value>
      <webElementGuid>ca0e5022-f76b-47c7-bdbd-79537257ad33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[95]</value>
      <webElementGuid>367ca0c4-35b3-4ad5-b195-aa4ac14aaafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li/a</value>
      <webElementGuid>12362b4e-36a7-47d8-b167-1277f7db2146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'United-Kingdom' and (text() = 'United Kingdom' or . = 'United Kingdom')]</value>
      <webElementGuid>8fadcf95-5df0-49de-a9b3-912911306ad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
