<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cookie PreferencesCookies may be used o_f66e1a</name>
   <tag></tag>
   <elementGuidId>8c00ac79-5717-4c48-9c32-7152539cfc1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onetrust-policy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#onetrust-policy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b551d400-3035-4461-8a54-709097267a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onetrust-policy</value>
      <webElementGuid>a7845e77-cf9b-4e5b-b209-ad7a472a3270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cookie PreferencesCookies may be used on this site and stored on your device to enhance site navigation, analyze site usage, enable troubleshooting session recording for optimized customer support resolution, and assist in our marketing efforts.Read our Cookie Policy</value>
      <webElementGuid>9c9bf2d9-d45d-4c40-9891-8236273f6ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onetrust-policy&quot;)</value>
      <webElementGuid>7451c935-9fb9-402e-9762-70e49f5686bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='onetrust-policy']</value>
      <webElementGuid>705e1654-8001-4391-9c68-8f4d7f93e56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onetrust-group-container']/div[2]</value>
      <webElementGuid>e65e92d0-868d-40d8-b8e3-95f6879db01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to Event Page'])[1]/following::div[15]</value>
      <webElementGuid>d6188f49-146f-4f3f-9a43-c4f021064747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter 3D Space'])[1]/following::div[15]</value>
      <webElementGuid>276f4dcb-54cd-4c9d-a413-3b128a1591f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div[2]</value>
      <webElementGuid>aa78fc4c-f7c4-4d2c-9d87-9dea9d0e5d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'onetrust-policy' and (text() = 'Cookie PreferencesCookies may be used on this site and stored on your device to enhance site navigation, analyze site usage, enable troubleshooting session recording for optimized customer support resolution, and assist in our marketing efforts.Read our Cookie Policy' or . = 'Cookie PreferencesCookies may be used on this site and stored on your device to enhance site navigation, analyze site usage, enable troubleshooting session recording for optimized customer support resolution, and assist in our marketing efforts.Read our Cookie Policy')]</value>
      <webElementGuid>5380c589-52f4-45ee-86b6-3a89060f3d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
