<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_OK_fal fa-folder</name>
   <tag></tag>
   <elementGuidId>a82fb47b-c4b9-47f4-849a-68d228aaea44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header-projectfolder']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fal.fa-folder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9cb9528a-8fc1-4e25-8f86-939a4a073f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fal fa-folder</value>
      <webElementGuid>53580d70-f169-4a06-97d4-c11026b3f48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-projectfolder&quot;)/i[@class=&quot;fal fa-folder&quot;]</value>
      <webElementGuid>438d10ea-6b34-4fb0-bed0-cdb94c3d0a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4ed93672-a495-47ff-aa07-30c8844c125c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fal fa-folder</value>
      <webElementGuid>1ab62b7b-63eb-4eef-9238-74724287486e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-projectfolder&quot;)/i[@class=&quot;fal fa-folder&quot;]</value>
      <webElementGuid>29f8c290-5ef3-429b-b4ab-5cc1c09a1e35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='header-projectfolder']/i</value>
      <webElementGuid>74ea7eed-439c-4fd4-8c9a-b6c95071fe5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/i</value>
      <webElementGuid>74609b89-50cd-4f04-ac66-2ae115f78c01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
