<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OK_black-version logo_js</name>
   <tag></tag>
   <elementGuidId>bc7acecd-c5c0-4e67-8479-5ebeb2ad9b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='utility-logo']/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.black-version.logo_js</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>510f7e69-3ead-445f-a612-38ddfa365fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/content/dam/kohler-kds/logoBlack.svg</value>
      <webElementGuid>ce726cc7-d6ed-4a66-8c57-38733ebed695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>64e82c44-fbd4-47e5-8dc9-971d82490425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>6dac8f57-835e-4db2-b491-89c01f7a07ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-version logo_js</value>
      <webElementGuid>f6f10aca-735b-4ce9-a7a0-0337136e37b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Studio KOHLER Logo Black</value>
      <webElementGuid>42a1c2ed-53d2-4000-8f32-6bb48c6feb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;utility-logo&quot;)/img[@class=&quot;black-version logo_js&quot;]</value>
      <webElementGuid>318b21e5-9aef-4c5c-808b-919109c1e308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='utility-logo']/img[2]</value>
      <webElementGuid>b3d2c0ce-10d7-4739-ac02-c0f0064404cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Studio KOHLER Logo Black']</value>
      <webElementGuid>709ce0b6-c672-4416-9a0d-a8094c4b5d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img[2]</value>
      <webElementGuid>539381c3-dc4e-48bd-9c05-e5d41aeb6607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/content/dam/kohler-kds/logoBlack.svg' and @alt = 'Studio KOHLER Logo Black']</value>
      <webElementGuid>600f09bc-d31d-485b-b16e-bd8493933ca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
