<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_nav-user-password</name>
   <tag></tag>
   <elementGuidId>6fa5ce6b-9a90-4d60-86f7-eae832a4cd81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-user-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-user-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5817f1ff-6bfd-4e6f-8ab1-db15bddbedca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f0c154e9-1124-49c2-a312-c496267edea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control navSignIn utility-color header-password-signin</value>
      <webElementGuid>3af6da64-b951-42f8-b5e2-3b25776b1a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-user-password</value>
      <webElementGuid>dca1db75-bbee-405a-bff5-beb7abda4440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d\W]{8,}$</value>
      <webElementGuid>774645b7-ca89-4109-93c8-3281e1451e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nav-user-password</value>
      <webElementGuid>f93eb28d-4ebb-4de4-97e7-e810020efa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-user-password&quot;)</value>
      <webElementGuid>0bd5460c-992c-46fc-99d9-0423d51bdf5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-user-password']</value>
      <webElementGuid>f390d106-35e8-43f3-8846-6d21542acbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-account']/div/div/div/div/div/form/div[2]/input</value>
      <webElementGuid>b77c4684-c2cd-4bd6-9356-043c3858d9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>308bbfaf-6757-4b57-9394-7fa59109e062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'nav-user-password' and @name = 'nav-user-password']</value>
      <webElementGuid>912eeded-4f8a-4bd8-9da0-7737225a17d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
