<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail Address_nav-user-email</name>
   <tag></tag>
   <elementGuidId>9c8b7e4b-6414-443a-894f-e9eaa19cd48a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-user-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-user-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36ff0ecb-9a61-42e0-a7da-b25097d970e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>dd90c62b-a457-4b52-ba9b-2e273584c354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>594a7c6d-37ff-4e0b-8e47-e1921b355db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-Z0-9.-_\-]{1,}@[a-zA-Z0-9.-]{2,}[.]{1}[a-zA-Z]{2,}</value>
      <webElementGuid>c1882b99-bc1a-48d1-9d01-0b4fa0102ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-email-signin form-control navSignIn utility-color</value>
      <webElementGuid>39315340-00c3-4046-9e7e-3e37877b80ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-user-email</value>
      <webElementGuid>aa7a3336-4cfc-4fba-826f-9ffca3e55a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nav-user-email</value>
      <webElementGuid>afbb0749-62a9-43e0-9923-f543703401a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-user-email&quot;)</value>
      <webElementGuid>e5cca434-76c6-400a-bd59-521cd814b75d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-user-email']</value>
      <webElementGuid>6cc58288-2a88-4870-ab2b-6e18a08e98cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-account']/div/div/div/div/div/form/div/input</value>
      <webElementGuid>6854a883-f564-4dbf-8fe1-0ae1a038cdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>865c2389-c8fc-4307-8364-636fae5a3c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'nav-user-email' and @name = 'nav-user-email']</value>
      <webElementGuid>ecaef6bb-1250-4d5d-83cb-0dd96d48ddbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
