<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BRAZIL</name>
   <tag></tag>
   <elementGuidId>b8caae7c-3a48-483d-aec3-a7709ba611f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='getStoreData(this)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pb-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c551e82-eb9b-4ade-9fcd-f7ffa77561d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8c072d18-3e85-4247-96ee-7acb97886bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pb-1</value>
      <webElementGuid>b06c4898-4e76-4cd6-aa3b-92696bffd18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>getStoreData(this)</value>
      <webElementGuid>d576ba90-5624-4611-94f7-311de34b3882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BRAZIL</value>
      <webElementGuid>34f32b30-8229-47d6-b3c3-d503f0c618e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page1&quot;)/div[@class=&quot;find-store kohler-store text-center&quot;]/div[@class=&quot;container find-a-store-map mt-4 pt-2&quot;]/div[@class=&quot;position-relative select-store&quot;]/div[@class=&quot;find-body&quot;]/div[@class=&quot;find-store-list col-lg-8 col-md-8 col-sm-12 mx-auto&quot;]/ul[@class=&quot;pl-lg-5 pl-sm-5 list-unstyled text-uppercase p-0&quot;]/li[@class=&quot;py-4 d-inline-block&quot;]/a[@class=&quot;pb-1&quot;]</value>
      <webElementGuid>a21094ba-c756-4a15-ac5c-159d6bf4c9e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='getStoreData(this)']</value>
      <webElementGuid>f629cc1c-e91d-4238-b958-74df53f8ce7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page1']/div/div[2]/div/div/div/ul/li/a</value>
      <webElementGuid>ebdb8ea9-0677-48b2-a691-879af9244764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BRAZIL')]</value>
      <webElementGuid>6234fe2e-f4c6-45bf-a6d4-b5c34083632e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Store Location'])[1]/following::a[1]</value>
      <webElementGuid>24618d76-0033-4016-88df-592b9bf6bbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Store'])[2]/following::a[1]</value>
      <webElementGuid>95e0c875-11f7-4415-828a-21ba2912fa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='false'])[1]/preceding::a[12]</value>
      <webElementGuid>c4d6fb16-add4-4b58-8e97-b33eed27948c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Stores'])[1]/preceding::a[12]</value>
      <webElementGuid>ba8746d1-5a7d-4c04-bb22-4d0e10685bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BRAZIL']/parent::*</value>
      <webElementGuid>f4cf9817-ed32-4112-944f-62fa4fe59bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[226]</value>
      <webElementGuid>3cccda26-7617-4999-9ecf-a8881b94341f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/div/ul/li/a</value>
      <webElementGuid>3ce0894d-e1bc-4038-b681-0d9bfb8676ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'BRAZIL' or . = 'BRAZIL')]</value>
      <webElementGuid>1fc11a15-7623-4413-9801-8cfb36c7e638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
