<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TAIWAN</name>
   <tag></tag>
   <elementGuidId>5a34d6f3-c485-4640-902d-7b1d05798560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='getStoreData(this)'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a1f17196-fe61-4988-b5b2-26f30d7857ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ef23de91-e7b2-4ef4-97d4-b1c571f22227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pb-1</value>
      <webElementGuid>4c6b6190-4aa8-40da-8d94-ce081aecba18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>getStoreData(this)</value>
      <webElementGuid>462bf9f0-cfd0-4665-ad43-0dd23e724fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TAIWAN</value>
      <webElementGuid>bbbf5205-ce35-489e-ad88-965ccd652dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page1&quot;)/div[@class=&quot;find-store kohler-store text-center&quot;]/div[@class=&quot;container find-a-store-map mt-4 pt-2&quot;]/div[@class=&quot;position-relative select-store&quot;]/div[@class=&quot;find-body&quot;]/div[@class=&quot;find-store-list col-lg-8 col-md-8 col-sm-12 mx-auto&quot;]/ul[@class=&quot;pl-lg-5 pl-sm-5 list-unstyled text-uppercase p-0&quot;]/li[@class=&quot;py-4 d-inline-block&quot;]/a[@class=&quot;pb-1&quot;]</value>
      <webElementGuid>58c32bd5-fb6d-4c3b-a075-3fd0ae6cd999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='getStoreData(this)'])[7]</value>
      <webElementGuid>9d6b8564-a8b8-4866-b5ad-29ffc147d06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page1']/div/div[2]/div/div/div/ul/li[7]/a</value>
      <webElementGuid>e550790f-f374-4692-a6fe-11785957f7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TAIWAN')]</value>
      <webElementGuid>08616c4b-2828-4647-bebe-1a5ea2bbb266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Store Location'])[1]/following::a[7]</value>
      <webElementGuid>a7c5cdd8-9994-4eaf-8fa3-6a7b430b5f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Store'])[2]/following::a[7]</value>
      <webElementGuid>c3ccb47b-5515-4ef9-b656-5dbbea297010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='false'])[1]/preceding::a[6]</value>
      <webElementGuid>e4c960dc-9052-4ab3-846f-72d79772f629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find A Store'])[1]/preceding::a[6]</value>
      <webElementGuid>7117318b-28e9-41ba-9a61-548e3ee8ed93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TAIWAN']/parent::*</value>
      <webElementGuid>58136f12-f1c3-4114-b8c1-0871ea8b760e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[232]</value>
      <webElementGuid>398efca8-1751-4c4f-abce-e36265b1b7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/div/ul/li[7]/a</value>
      <webElementGuid>b78fab41-60e3-4a8c-9528-1b2bd3019bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'TAIWAN' or . = 'TAIWAN')]</value>
      <webElementGuid>374b9c1f-f007-4ba2-93b9-74eb9dc296a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
