<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail Address_nav-user-email</name>
   <tag></tag>
   <elementGuidId>a3d352ac-eb87-44a7-a14d-697175d0cfff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-user-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-user-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd8641c1-b21f-42fd-b9b1-b4bd39e96f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5ad74dbc-982e-496e-8a62-e0e5182c3621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d1960f2f-41dd-4b54-a953-2096a9ff29ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-Z0-9.-_\-]{1,}@[a-zA-Z0-9.-]{2,}[.]{1}[a-zA-Z]{2,}</value>
      <webElementGuid>018ff022-491f-4ed1-9e96-f4be0b7e1b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-email-signin form-control navSignIn utility-color</value>
      <webElementGuid>9d2b5170-830b-44cb-859e-e2539b9395d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-user-email</value>
      <webElementGuid>859f5ab3-179a-417d-bb4d-d3d813b4e2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nav-user-email</value>
      <webElementGuid>14192f80-c007-474f-a5b9-22ad80fc3fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-user-email&quot;)</value>
      <webElementGuid>833926ec-858e-4e38-9f1b-f67435cda4d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-user-email']</value>
      <webElementGuid>5424c921-9f08-41b9-8abf-66f1ca711b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-account']/div/div/div/div/div/form/div/input</value>
      <webElementGuid>b61516bd-01c3-4bd3-8902-9f40f2cab350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>113d0cb4-39e3-4dcb-b921-40a89cf4442e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'nav-user-email' and @name = 'nav-user-email']</value>
      <webElementGuid>bd531413-7134-4c17-b213-468d91cb14cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
