<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_nav-user-password</name>
   <tag></tag>
   <elementGuidId>5820daae-4f3a-4e3f-8879-6186349d380f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-user-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-user-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>293e3064-8194-4b33-9e97-491bb60bac43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>359e427e-30f6-40af-a149-8da13d4c6205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control navSignIn utility-color header-password-signin</value>
      <webElementGuid>38e0c6ca-0911-4c86-aba0-60dbf3b2ce1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-user-password</value>
      <webElementGuid>803d2609-71af-4c79-a4e6-ca00c773a2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d\W]{8,}$</value>
      <webElementGuid>482a88d5-cbfc-43c1-a9f2-53bb305a6e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nav-user-password</value>
      <webElementGuid>b877e7a4-91f6-452f-97dd-3804ff4ae5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-user-password&quot;)</value>
      <webElementGuid>ea59fc29-85a8-4997-b7df-02da720608bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-user-password']</value>
      <webElementGuid>1bd9274b-c599-44c9-aa0c-2df1e912d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-account']/div/div/div/div/div/form/div[2]/input</value>
      <webElementGuid>f0b03204-9bcc-4bd8-a36f-b6c51b184bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>3cbd83d3-7d26-4fd2-aba5-69dfa751dc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'nav-user-password' and @name = 'nav-user-password']</value>
      <webElementGuid>ab6af750-7c72-4408-811b-892cacfbe500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
