<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_IE BUMPER_gsftmain</name>
   <tag></tag>
   <elementGuidId>7aa2cc85-9353-407a-b9b3-2337ae4024fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gsftmain</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsftmain']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e2bef833-68c9-4879-81f9-ca83b7dc0615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>39ffdbdd-cd89-4deb-85a4-fb23d1fb1bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1403</value>
      <webElementGuid>b42e8fe0-c5c2-4969-bddb-3869c0a45ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gsftmain</value>
      <webElementGuid>b2152b1c-6af5-49f9-bf2e-24170b9d7d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsftmain</value>
      <webElementGuid>75723c61-3114-4e5b-9a40-31d0f58f5284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4fc97772-f4b4-4fdc-883c-4f9a2d2ed0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>906db902-d816-4a73-86d6-212df7df316c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e334f6ed-b6d6-4cc2-b32c-37dfe11f242a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>com.glideapp.servicecatalog_cat_item_view.do?sysparm_clear_stack=yes&amp;sysparm_id=a25bb6e113d22f00ff1256722244b07b&amp;sysparm_nameofstack=08c3883c47ff615099e2a688436d43a1</value>
      <webElementGuid>85a3b5b1-64fa-43ac-8893-46f846782ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>74ba10fe-9591-4e5b-a21b-3b5245c7a79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsftmain&quot;)</value>
      <webElementGuid>18e66b15-47b5-4b95-9e65-e89eef79d0e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsftmain']</value>
      <webElementGuid>6dde3e02-56e6-4f4d-a883-b79feadebe04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dropzone10']/div/iframe</value>
      <webElementGuid>cde90826-7b5f-44c8-b3a6-cef1a9457d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5005977b-5968-4c4d-be19-5b74d9d8be58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'gsftmain' and @id = 'gsftmain' and @src = 'com.glideapp.servicecatalog_cat_item_view.do?sysparm_clear_stack=yes&amp;sysparm_id=a25bb6e113d22f00ff1256722244b07b&amp;sysparm_nameofstack=08c3883c47ff615099e2a688436d43a1']</value>
      <webElementGuid>fdf1b129-768b-4555-b69a-ce708feeb1eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
