<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KOHLER Subject Access Request</name>
   <tag></tag>
   <elementGuidId>38bd228d-c366-47fe-8ed8-e62ae12e0538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.guide_tray > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='item_table']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c858e660-293c-4403-8659-441da20f515b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>25eee008-fddc-47f4-9a1b-a43fb1a96800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2267af01-64ec-467c-8a93-596882fff6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOHLER Subject Access Request</value>
      <webElementGuid>29a046a7-dad1-4033-82f9-c56cfb64db18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_table&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;guide_tray&quot;]/span[1]</value>
      <webElementGuid>8077a32e-8dbf-4e24-a1e9-c253992702af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KSD/Page_GDP Form/iframe_IE BUMPER_gsftmain</value>
      <webElementGuid>ad917fa6-9d0f-4494-97bc-540ebec7f257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='item_table']/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/span</value>
      <webElementGuid>d343791f-da41-456c-b274-9127c796c79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ -3'])[1]/following::span[1]</value>
      <webElementGuid>b7984a51-e8ec-4815-8a1e-ed77945b7f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Attachments'])[1]/following::span[4]</value>
      <webElementGuid>547026ab-3b32-4d70-8b57-44bfcd963528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::span[3]</value>
      <webElementGuid>e8cbdcf0-d38d-451d-a00a-80f5f764118c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>fcf2356b-0f98-48c9-abd5-4b3b0cb1c971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KOHLER Subject Access Request' or . = 'KOHLER Subject Access Request')]</value>
      <webElementGuid>fc6425d6-e946-484d-b9af-9ba7c711b136</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
