<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Accept</name>
   <tag></tag>
   <elementGuidId>a29f2f50-adda-4600-84eb-bc087a9de3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sm-visitor-app-container']/div/div/div/span/div/div[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4db36209-3043-4a58-8bf6-29dcecb89e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sm-formatted-html-message</value>
      <webElementGuid>b677a357-7e57-42dc-90bd-97736aca131a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>97c8fca3-e7e3-4c2b-9092-2d4338a71407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-visitor-app-container&quot;)/div[1]/div[@class=&quot;sm-touch-draggable-placeholder&quot;]/div[@class=&quot;sm-visitor-app&quot;]/span[1]/div[@class=&quot;sm-inner sm-incoming-call&quot;]/div[@class=&quot;sm-button sm-animated sm-positive-button sm-div-button&quot;]/span[@class=&quot;sm-formatted-html-message&quot;]</value>
      <webElementGuid>1de8fa6a-8d80-4a12-a00a-e94861fc17ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sm-visitor-app-container']/div/div/div/span/div/div[5]/span</value>
      <webElementGuid>53343bb4-0750-4497-9be0-7ed1a9d43a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/following::span[1]</value>
      <webElementGuid>25306dce-c5e1-4f63-ac3f-2d60ba556507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to StudioKohler.com. Can I assist you with any questions?'])[1]/following::span[2]</value>
      <webElementGuid>124ffa60-a85d-43e3-9fd8-57c5b594f733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>cbf8812d-c8bf-4751-b61e-b040d5fb2c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]/span</value>
      <webElementGuid>8d625abb-3485-4536-821b-c312082eb5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>a8a17dc0-2702-4afc-9bfa-5ecec091f8ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
