<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_test folder_fal fa-trash-alt</name>
   <tag></tag>
   <elementGuidId>3d49f8b2-352b-40ff-b747-465da9a57d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dynamic-folders']/div[2]/div/p/a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fal.fa-trash-alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c44dd61e-8c39-4a48-beca-97380bbff080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fal fa-trash-alt</value>
      <webElementGuid>f03f4eb5-3c83-46df-9182-109a21d9e337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamic-folders&quot;)/div[@class=&quot;col-12 col-md-6 col-lg-4 dynamic-created-folder&quot;]/div[@class=&quot;details position-relative&quot;]/p[1]/a[@class=&quot;primary-color delete-folder&quot;]/i[@class=&quot;fal fa-trash-alt&quot;]</value>
      <webElementGuid>1894aeb2-ef66-420d-ba0f-75c1bdae5ff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dynamic-folders']/div[2]/div/p/a[2]/i</value>
      <webElementGuid>5548f641-b4f4-41be-a55e-241a8b7a6d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a[2]/i</value>
      <webElementGuid>7d7b8ff6-47c6-4b3b-9c90-bd88dab65726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
