<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Folder Name_create-folder-name</name>
   <tag></tag>
   <elementGuidId>1802a558-3864-4d46-9657-ee6ccbee2117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='create-folder-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create-folder-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c74c4495-fe17-4a6f-b005-35baff8ed040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>714d71f5-1a11-4f0b-95f3-4b25d88e3d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control create-focus</value>
      <webElementGuid>50ee137d-9efd-41ae-9e59-cfa1a601dd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(?!\s*$)[\w,'\.\$\s]*$</value>
      <webElementGuid>a3cf55f4-ec2a-4e57-ad8d-dc1134684c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9ed806a7-6e2c-4b61-8925-a0e4185f7031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-folder-name</value>
      <webElementGuid>a7140135-8c99-4f2e-b94a-d455465d79bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create-folder-name</value>
      <webElementGuid>baea7e17-8dd6-42ee-8c60-f7f94eaa97db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-folder-name&quot;)</value>
      <webElementGuid>1a49b582-7725-4cb3-806b-f2dd08adb940</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='create-folder-name']</value>
      <webElementGuid>08413ba0-c289-4d62-a5cb-41474e51b3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create-modal']/div/div/div/form/div/input</value>
      <webElementGuid>f60e73ae-358f-4223-a7f8-2d4ae6e461d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/form/div/input</value>
      <webElementGuid>e57db804-e5fa-4b26-a405-3896aa5e918c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'create-folder-name' and @name = 'create-folder-name']</value>
      <webElementGuid>21ef91e5-36f6-4599-9416-0be655a3c353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
