<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Project Folder Details_create-note</name>
   <tag></tag>
   <elementGuidId>0a914191-eefe-4b28-b9a2-fc3fb3cd575e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='create-note']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create-note</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7906f053-e86c-421a-92e5-a3fc96a0fd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-count create-focus pattern-1</value>
      <webElementGuid>4cd090ac-85c5-4c47-8266-e3413eda1759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>e4ad8b2c-dd7f-48d4-8633-f56e5488e13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-note</value>
      <webElementGuid>f482b828-2805-4543-8cae-1a8344381f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create-note</value>
      <webElementGuid>4fa189af-d26c-4067-afa4-0ff55f5ed8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>79e3040d-0749-44e9-b443-af591838af69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-note&quot;)</value>
      <webElementGuid>1947b14c-2966-41ee-8f3d-1b7dcc340d05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='create-note']</value>
      <webElementGuid>41aabbf4-7f96-4979-b335-9693453e0909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create-modal']/div/div/div/form/div[2]/textarea</value>
      <webElementGuid>b0d1d038-096f-499b-818c-a84d2ca1d2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/form/div[2]/textarea</value>
      <webElementGuid>de3bdcd0-2954-4728-9b40-1df8f14c6008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'create-note' and @name = 'create-note']</value>
      <webElementGuid>14bb4c0b-e656-48cc-9dcf-3dca8d5bb5b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
