<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Orders</name>
   <tag></tag>
   <elementGuidId>42c40097-9ce2-438b-bb24-98d81de3006c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-orders']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-orders > span.nav-line-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e8bf3cd-ae98-4d77-96cb-3e43cace3527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-line-2</value>
      <webElementGuid>297c3430-009d-42bf-ae67-232f49d69008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&amp; Orders</value>
      <webElementGuid>da83baad-9be4-42e9-8853-7e437ec02afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-orders&quot;)/span[@class=&quot;nav-line-2&quot;]</value>
      <webElementGuid>59dbf6a6-9e25-4c6e-8f3f-4b42832a186e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-orders']/span[2]</value>
      <webElementGuid>0b57565a-c0bf-4ddb-b8b2-6165c09cbfdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Returns'])[1]/following::span[1]</value>
      <webElementGuid>eaf93998-c8bf-4327-bf8c-d958fa6934ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Bhushan? Sign Out'])[1]/following::span[2]</value>
      <webElementGuid>f71f7557-1e3e-443a-9eaf-d3fc1b3dbb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Lists'])[1]/preceding::span[7]</value>
      <webElementGuid>17c52fab-475d-4a20-9e91-39f8fc24108d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a Wish List'])[1]/preceding::span[7]</value>
      <webElementGuid>11bec075-eb4c-4270-8a48-f9c84bedb73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&amp; Orders']/parent::*</value>
      <webElementGuid>73de0613-dfd8-4f78-98a6-4e6a601e85b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/span[2]</value>
      <webElementGuid>f68827ae-b2db-4b55-8471-bff448153bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '&amp; Orders' or . = '&amp; Orders')]</value>
      <webElementGuid>3aa840a1-2eb5-4b10-81ad-9e18f95fc6f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
