<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Relevancy</name>
   <tag></tag>
   <elementGuidId>84bdfa17-f618-4e35-be12-9ceba3072607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filter-dropdown']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.body1-typ.d-block.py-md-2.down-arrow.border-0.text-left.most-view.font-weight-normal.selected.color-black.drop-header.pl-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>160dd4f8-0a75-4241-b57b-c17cef2fb37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>body1-typ d-block py-md-2 down-arrow border-0 text-left most-view font-weight-normal selected color-black drop-header pl-2</value>
      <webElementGuid>c5a57870-8149-42e5-9ad4-dd8c5e1d026b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>53133396-d553-456e-94c7-2160be7da738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Relevancy
										
									</value>
      <webElementGuid>f4f0b7c0-c2b2-4bb0-8958-2744c504539c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-dropdown&quot;)/a[@class=&quot;body1-typ d-block py-md-2 down-arrow border-0 text-left most-view font-weight-normal selected color-black drop-header pl-2&quot;]</value>
      <webElementGuid>672e908d-dfde-41fe-bfa8-c84906460074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-dropdown']/a</value>
      <webElementGuid>87fc6be0-98e0-4875-a3d6-94e59e8fb6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter By'])[2]/following::a[1]</value>
      <webElementGuid>7e38b9d9-b851-4a88-9443-35cb299da541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Products'])[1]/following::a[3]</value>
      <webElementGuid>97af2bac-8179-4132-804a-52c4bc2241e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Relevancy']/parent::*</value>
      <webElementGuid>25fcc1b7-9434-4616-97e8-55df3418ec30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>fbeadc77-0b9a-4c41-9bf3-859297f4321e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
										Relevancy
										
									' or . = '
										Relevancy
										
									')]</value>
      <webElementGuid>612e5559-51a2-44f5-9ef3-107f81f41e72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
