<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Articles</name>
   <tag></tag>
   <elementGuidId>2f9359b5-a8ed-41be-adcc-74e648a6e87e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-collapsenav']/ul/li[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.nav-item.articles-tab > a.nav-link.border-0.p-0.pr-md-5 > span.pb-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f5430317-2ca3-430a-9f14-d774ed14a160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pb-1</value>
      <webElementGuid>c6d5049f-8938-443b-96da-ab11121d3aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Articles</value>
      <webElementGuid>4b58664f-7441-43d3-864e-23876ed405a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-collapsenav&quot;)/ul[@class=&quot;nav nav-tabs w-100 text-uppercase border-0 flex-md-row&quot;]/li[@class=&quot;nav-item articles-tab&quot;]/a[@class=&quot;nav-link border-0 p-0 pr-md-5&quot;]/span[@class=&quot;pb-1&quot;]</value>
      <webElementGuid>a53e1eba-374f-4edc-8438-7fb304428a75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-collapsenav']/ul/li[3]/a/span</value>
      <webElementGuid>bce5531b-cacc-4e22-b217-446dca1a6935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(111)'])[1]/following::span[1]</value>
      <webElementGuid>09dea036-d66a-4da7-991b-25f98697f051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Specifications'])[4]/following::span[2]</value>
      <webElementGuid>2a4c0c10-600e-40e6-998d-09130287a7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(68)'])[1]/preceding::span[1]</value>
      <webElementGuid>681af68e-d45d-4e8e-b3a2-17440525b917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Category'])[1]/preceding::span[2]</value>
      <webElementGuid>f37a34a1-bd64-4b56-bfbb-66ea9e124280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Articles']/parent::*</value>
      <webElementGuid>48e8c01e-1612-44f9-a554-fd95fd973a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li[3]/a/span</value>
      <webElementGuid>6a42de32-f8d2-4d12-9bcf-675f6e980837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Articles' or . = 'Articles')]</value>
      <webElementGuid>65885522-f707-4899-9194-5b0b19ac6e63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
