<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Products</name>
   <tag></tag>
   <elementGuidId>12810947-b021-4081-8e2a-39ca3e17120b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-collapsenav']/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pb-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f2811fd5-aa30-4966-97c9-2d4bc9cf9e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pb-1</value>
      <webElementGuid>497dc17d-f653-4617-b557-8e38abeeacb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>066e7f0d-e81e-4b6b-983a-e608bf130b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-collapsenav&quot;)/ul[@class=&quot;nav nav-tabs w-100 text-uppercase border-0 flex-md-row&quot;]/li[@class=&quot;nav-item products-tab&quot;]/a[@class=&quot;nav-link border-0 p-0 pr-md-5 active&quot;]/span[@class=&quot;pb-1&quot;]</value>
      <webElementGuid>9a3dc4c5-3d36-4799-9f96-195b78665e3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-collapsenav']/ul/li/a/span</value>
      <webElementGuid>408d6186-e913-4d22-a3c5-577bf4decfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[2]/following::span[2]</value>
      <webElementGuid>4abd3435-5eaf-4eba-b031-7aa015dc1218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(129)'])[1]/preceding::span[1]</value>
      <webElementGuid>b9678fa9-a065-4240-acdf-43930e309cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Specifications'])[4]/preceding::span[2]</value>
      <webElementGuid>1dd39b9d-8f5a-4441-974d-3af64d99e5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li/a/span</value>
      <webElementGuid>8455b118-0b8d-4133-b46a-cf4aa29edbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Products' or . = 'Products')]</value>
      <webElementGuid>511c9313-06b1-4221-9679-a01410577fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
