<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete Folder</name>
   <tag></tag>
   <elementGuidId>417ab961-a013-4405-b47f-7b15ca4f93e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[80]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.col-md-6.btn.submit.btn-primary.btn-black.float-right.mb-3.mb-md-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6dda7ffe-9db2-4211-b7e3-bd112c63f4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21d8b7a3-ea7b-4a86-bfa8-36abbd50c9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6 btn submit btn-primary btn-black float-right mb-3 mb-md-auto</value>
      <webElementGuid>321f81be-0d3c-44f4-b04a-71422f915427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-folder-name</name>
      <type>Main</type>
      <value>First Folder</value>
      <webElementGuid>5f0d6262-fc6c-48a0-a8aa-b85deb046eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Folder</value>
      <webElementGuid>91a40702-b8a2-4251-b99f-5428a927b232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;del-folder-modal&quot;)/div[@class=&quot;modal-dialog mx-auto&quot;]/div[@class=&quot;modal-content rounded-0 border-0&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;del-folder-form&quot;]/div[@class=&quot;footers text-md-right pt-4&quot;]/button[@class=&quot;col-md-6 btn submit btn-primary btn-black float-right mb-3 mb-md-auto&quot;]</value>
      <webElementGuid>5fcaca52-0aaa-4e49-b69b-e2d7753304b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[80]</value>
      <webElementGuid>eb094e68-e973-48e4-8091-3cce142363f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='del-folder-modal']/div/div/div/form/div[2]/button</value>
      <webElementGuid>a9b65eaf-177e-45d6-af25-ed43f6bf6f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Folder'])[6]/following::button[1]</value>
      <webElementGuid>312598af-3bdb-4541-95d5-9fcce1b5fb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[31]/preceding::button[1]</value>
      <webElementGuid>958a8ab8-a74a-4dc3-9ef0-e14bb999a286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WeChat'])[1]/preceding::button[3]</value>
      <webElementGuid>c19f6e0f-b391-4823-8bd2-9c7e87063f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete Folder']/parent::*</value>
      <webElementGuid>9402370a-d63d-4a49-879d-c2d682108d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/form/div[2]/button</value>
      <webElementGuid>3de1c7a2-0c4a-443d-9127-6aa1681b4766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Delete Folder' or . = 'Delete Folder')]</value>
      <webElementGuid>23bd723d-9d1d-42ec-bae5-6d73801bbeb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
