<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Folder</name>
   <tag></tag>
   <elementGuidId>9c34b1d5-0764-4ea8-9405-c8496c7d6a4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[33]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.footers.text-md-right.pt-4 > button.col-md-5.btn.btn-primary.btn-black.submit.float-right.mb-3.mb-md-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3550be9c-9a5b-4069-81e3-134d445ad338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4f828269-4a5e-40b3-8e36-59ce2a858571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-5 btn btn-primary btn-black submit float-right mb-3 mb-md-auto</value>
      <webElementGuid>6e7af5e0-8de1-45c5-af6f-982afc6aa650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Folder</value>
      <webElementGuid>6493fc49-b086-4f9e-b153-8054e260302d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-modal&quot;)/div[@class=&quot;modal-dialog mx-auto&quot;]/div[@class=&quot;modal-content rounded-0 border-0 h-100&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;create-form&quot;]/div[@class=&quot;footers text-md-right pt-4&quot;]/button[@class=&quot;col-md-5 btn btn-primary btn-black submit float-right mb-3 mb-md-auto&quot;]</value>
      <webElementGuid>1ed341e6-5eaa-45d3-8594-cb54ba052a0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[33]</value>
      <webElementGuid>724c2b1b-a09f-450b-84f9-3a4f3f35c00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create-modal']/div/div/div/form/div[3]/button</value>
      <webElementGuid>a414474a-d0d7-4282-8b30-aaa5b89653a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/140'])[7]/following::button[1]</value>
      <webElementGuid>fa2a8c33-9861-4fca-be7f-6680b38d8756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Enter a Valid Note'])[6]/following::button[1]</value>
      <webElementGuid>89cd41b0-fb3b-4749-8b6c-8f01470a61ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[21]/preceding::button[1]</value>
      <webElementGuid>53347ed9-dfc8-4cc3-ac60-1dcabd4f7c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a Project Folder'])[1]/preceding::button[3]</value>
      <webElementGuid>29d7f1cc-2ebd-4a0a-a184-c47bf567911d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Folder']/parent::*</value>
      <webElementGuid>14f1ced8-f4b8-4bc9-b0f8-ebcf8081e175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/form/div[3]/button</value>
      <webElementGuid>88020c2a-7fbd-408c-8aa8-fa2c4776a70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Create Folder' or . = 'Create Folder')]</value>
      <webElementGuid>a38dab06-41a7-4767-ae97-f36b0844733c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
