<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_First Folder</name>
   <tag></tag>
   <elementGuidId>11bf469d-62e8-45ee-8019-0c1a396e0e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dynamic-folders']/div[2]/div/a/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>44f6ecfe-9ee0-424d-9697-5f1f4b334964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-uppercase</value>
      <webElementGuid>9a4fd751-ed3d-485f-8d5d-24b2d5bf6215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First Folder</value>
      <webElementGuid>17f33d8c-605d-4170-a228-1511b5c00f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamic-folders&quot;)/div[@class=&quot;col-12 col-md-6 col-lg-4 dynamic-created-folder&quot;]/div[@class=&quot;details position-relative&quot;]/a[@class=&quot;primary-color&quot;]/h2[@class=&quot;text-uppercase&quot;]</value>
      <webElementGuid>5bf8f080-1fd0-4fa5-a5d5-b5d00d627eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dynamic-folders']/div[2]/div/a/h2</value>
      <webElementGuid>fe895457-f7b8-4555-91d7-ef05ee5b92d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create new folder'])[1]/following::h2[1]</value>
      <webElementGuid>2a96d757-a4a6-4451-b6d2-e02d167cd7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share with Store'])[1]/preceding::h2[1]</value>
      <webElementGuid>e74d26fa-568f-49a5-99ad-7aa1f096df5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[3]/preceding::h2[2]</value>
      <webElementGuid>04ecfdf1-6205-408f-935a-d2a9f90d563a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/h2</value>
      <webElementGuid>f32e0f39-889d-4c59-98b5-fe5f4380ab6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'First Folder' or . = 'First Folder')]</value>
      <webElementGuid>661f9cf4-5d33-4c9e-a877-21411e6c0297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
