<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Folder Name_create-folder-name</name>
   <tag></tag>
   <elementGuidId>008ea4d8-cb9d-4f4a-be2f-bf899c9bdeb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='create-folder-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create-folder-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c17e065d-22ec-46dd-80b8-9152672884f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b332144-98d7-403a-9bf3-e6d54d1fb057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control create-focus</value>
      <webElementGuid>4b25cc04-85a1-435b-8fba-45467e04ec30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(?!\s*$)[\w,'\.\$\s]*$</value>
      <webElementGuid>fb8a1bd5-e54c-4691-a53a-27222023de1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>6bf897d0-0662-4218-a8f0-30ebec8030a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-folder-name</value>
      <webElementGuid>54b0da11-9998-48d4-8253-6a2df894a93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create-folder-name</value>
      <webElementGuid>e8a4aa57-d527-4ebc-b8fb-67203fe7d23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-folder-name&quot;)</value>
      <webElementGuid>2ae5a306-9d29-4f3c-8dfb-69c0b4101202</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='create-folder-name']</value>
      <webElementGuid>fe21f1b9-bb4c-4d52-961c-2b6cb7d0211c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create-modal']/div/div/div/form/div/input</value>
      <webElementGuid>02105cbf-93ce-4731-98ee-d21e115f5dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/form/div/input</value>
      <webElementGuid>ed47a7cc-507c-44da-9768-1cfcd956dfb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'create-folder-name' and @name = 'create-folder-name']</value>
      <webElementGuid>a2ca344f-168a-4fa8-94aa-c873ba6b3416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
