<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Project Folder Details_create-note</name>
   <tag></tag>
   <elementGuidId>2a007396-1b6c-4b3b-aa45-d0e6d09986d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='create-note']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create-note</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5fbe4422-cb91-4738-9fc8-3d7fda21a7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-count create-focus pattern-1</value>
      <webElementGuid>1630eb78-14a5-4db3-b30b-3fba93b95890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>e22e482d-385b-4ebd-8dac-1250505f861c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-note</value>
      <webElementGuid>f0000cd5-3ca3-4218-a682-9b69d8855785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create-note</value>
      <webElementGuid>6432a22a-fa69-4a11-8537-224b05f38673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f6918252-c097-472d-8838-8e44a5a64e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-note&quot;)</value>
      <webElementGuid>1e7d2b15-4a85-43cf-b86b-aa673b72efed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='create-note']</value>
      <webElementGuid>809bbaf7-eb96-4878-a3f7-8ef262a5cbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create-modal']/div/div/div/form/div[2]/textarea</value>
      <webElementGuid>8eff1de6-092c-4f7b-a5c5-def5311aefa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/form/div[2]/textarea</value>
      <webElementGuid>78bbe0f9-05c5-4a5e-bc2c-f95d44ac2513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'create-note' and @name = 'create-note']</value>
      <webElementGuid>ca8f3cca-2b12-4e18-a905-3c815f7b982c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
