<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1000.00</name>
   <tag></tag>
   <elementGuidId>c1d4c589-7b22-4eb7-9ecc-8aa737e674ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='APayBalance']/div/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.currency-green</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>811ecc36-99ac-4aeb-9d3c-e992042ef727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>currency-green</value>
      <webElementGuid>7d590e77-4d3b-402c-ad23-18cc57f56330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            ₹1000.00
        </value>
      <webElementGuid>65c90d27-b138-4e88-9526-3807f49b03cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;APayBalance&quot;)/div[@class=&quot;a-section onep-instrument-balance-desktop&quot;]/div[@class=&quot;a-row&quot;]/div[@class=&quot;a-column a-span4 a-text-right onep-instrument-amount-desktop a-span-last&quot;]/span[@class=&quot;currency-green&quot;]</value>
      <webElementGuid>254e2128-356c-462b-b92c-3a16fd6dd99b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='APayBalance']/div/div/div[2]/span</value>
      <webElementGuid>03f59378-93bb-47ed-92a7-fb4b5021f78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon Pay balance'])[1]/following::span[1]</value>
      <webElementGuid>cf3fc384-4c9c-4a65-ab62-ad73f5f4ccf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Sellers'])[1]/following::span[2]</value>
      <webElementGuid>bf4efd2d-4eb2-460a-8a13-d813233734a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Money'])[1]/preceding::span[1]</value>
      <webElementGuid>f0abb19d-25bc-4ae0-a804-668f3c5b2f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Gift Card'])[1]/preceding::span[3]</value>
      <webElementGuid>4f8ce3f2-ec8d-4ce9-93bc-9109ec37e385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='₹1000.00']/parent::*</value>
      <webElementGuid>165707cb-46a6-48b6-9aa3-b5c5c58f33a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/span</value>
      <webElementGuid>32338eec-5801-4aea-9bfb-f8ade5a8320f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
            ₹1000.00
        ' or . = '
            ₹1000.00
        ')]</value>
      <webElementGuid>471cfe86-f310-491b-9673-e9136259135b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
